[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.21"
optimizer = true
optimizer_runs = 100
via_ir = true
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
